spring.application.name=pnpe-backend
spring.profiles.active=local
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/pnpe_demo_dbd?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Libreville
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=${APP_JWT_SECRET:VGhpc0lzQVN0cm9uZ0RldmVsb3BtZW50S2V5Rm9yUE5QRUJhY2tlbmQxMjM0NTY3ODkw}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}

app.storage.root=${APP_STORAGE_ROOT:uploads/pnpe-documents}