package com.pnpe.backend.model.enums;

public enum CounselorActionType {
    WELCOME_ORIENTATION,
    PRE_REGISTRATION_REVIEW,
    DOCUMENT_VERIFICATION,
    PROJECT_STABILIZATION,
    VALIDATION,
    ACTION_PLAN_CREATED,
    FOLLOW_UP_CALL,
    INTERVIEW_PROPOSAL,
    INTERVIEW_FEEDBACK,
    TRAINING_ORIENTATION,
    STATUS_CHANGE,
    NOTE,
    ESCALATION
}
